export const tempMusicData = [
  {
    id: 1,
    title: "Imagine",
    artist: "John Lennon",
    genre: "Rock",
    rating: 5,
  },
  {
    id: 2,
    title: "Bohemian Rhapsody",
    artist: "Queen",
    genre: "Rock",
    rating: 4,
  },
  {
    id: 3,
    title: "Hey Jude",
    artist: "The Beatles",
    genre: "Pop Rock",
    rating: 5,
  },
  {
    id: 4,
    title: "A Change Is Gonna Come",
    artist: "Sam Cooke",
    genre: "Soul",
    rating: 5,
  },
  {
    id: 5,
    title: "Respect",
    artist: "Aretha Franklin",
    genre: "R&B, Soul",
    rating: 5,
  },
  {
    id: 6,
    title: "What a Wonderful World",
    artist: "Louis Armstrong",
    genre: "Jazz",
    rating: 5,
  },
  {
    id: 7,
    title: "Like a Rolling Stone",
    artist: "Bob Dylan",
    genre: "Rock",
    rating: 4,
  },
  {
    id: 8,
    title: "I Will Survive",
    artist: "Gloria Gaynor",
    genre: "Disco",
    rating: 4,
  },
  {
    id: 9,
    title: "Billie Jean",
    artist: "Michael Jackson",
    genre: "Pop, R&B",
    rating: 5,
  },
  { id: 10, title: "Purple Rain", artist: "Prince", genre: "Rock", rating: 5 },
  {
    id: 11,
    title: "Smells Like Teen Spirit",
    artist: "Nirvana",
    genre: "Grunge",
    rating: 4,
  },
  {
    id: 12,
    title: "Lose Yourself",
    artist: "Eminem",
    genre: "Hip Hop",
    rating: 5,
  },
  {
    id: 13,
    title: "Singin' in the Rain",
    artist: "Gene Kelly",
    genre: "Musical",
    rating: 4,
  },
  {
    id: 14,
    title: "Yesterday",
    artist: "The Beatles",
    genre: "Pop Rock",
    rating: 5,
  },
  {
    id: 15,
    title: "Hallelujah",
    artist: "Leonard Cohen",
    genre: "Folk",
    rating: 4,
  },
  {
    id: 16,
    title: "Bridge Over Troubled Water",
    artist: "Simon & Garfunkel",
    genre: "Folk Rock",
    rating: 5,
  },
  {
    id: 17,
    title: "A Song for You",
    artist: "Donny Hathaway",
    genre: "Soul",
    rating: 5,
  },
  {
    id: 18,
    title: "What a Difference a Day Makes",
    artist: "Dinah Washington",
    genre: "Jazz",
    rating: 4,
  },
  {
    id: 19,
    title: "Let It Be",
    artist: "The Beatles",
    genre: "Pop Rock",
    rating: 4,
  },
  {
    id: 20,
    title: "Hotel California",
    artist: "Eagles",
    genre: "Rock",
    rating: 5,
  },
];
